spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: base-backend
    profiles:
      active: dev

  jpa:
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true

#spring:
  #flyway:
   #enabled: true
   #baseline-on-migrate: false
   #validate-on-migrate: true
   #clean-disabled: true
   #out-of-order: false
   #placeholders:
    #app: base-backend
