server:
  port: 8082   # Cambio el puerto porque 8080 está ocupado

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base_backend?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8 # si el puerto también está ocupado, hay que cambiarlo
    username: root
    password: # vacío si no manejas password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # valida el esquema contra las entidades
    show-sql: true         # muestra las queries en consola
    open-in-view: false
    properties:
      hibernate:
        format_sql: true   # formateo de queries para mayor legibilidad
        jdbc.time_zone: UTC
    database-platform: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration   # carpeta donde habitan los scripts FlyWay
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 1
    clean-disabled: true
